target 'iosApp' do
  use_frameworks!
  platform :ios, '15.2'
  pod 'shared', :path => '../shared'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.2'
  end
 end
end